name = "exact_dynamics"
uuid = "b8b4104f-3b2f-4063-aa48-52782a6be98b"
authors = ["ultimatile <ultimatile@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
